on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: "Shellcheck"
env:
  VERSION: v0.8.0

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install shellcheck
        run: |
          wget -q https://github.com/koalaman/shellcheck/releases/download/$VERSION/shellcheck-$VERSION.linux.x86_64.tar.xz \
            -O shellcheck.tar.xz
          tar -xf shellcheck.tar.xz
          mv shellcheck-$VERSION/shellcheck .
          rm -rf shellcheck.tar.xz shellcheck-$VERSION

      - name: Run Shellcheck
        run: |
          ./shellcheck --version
          ./shellcheck -e SC2148 wt completions/*
